version: "3.9"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_PASSWORD=tile_generator
      - POSTGRES_USER=tile_generator
      - POSTGRES_DB=tile_generator
    ports:
      - 5432:5432

  pghero:
    image: ankane/pghero
    container_name: pghero
    network_mode: host
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://tile_generator:tile_generator@localhost:5432
    volumes:
      - ./pghero.yml:/app/config/pghero.yml
